//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// Nom du fichier d'origine :
// Date de génération : 06/01/2020 09:52:36
namespace Agenda.FuchsEntities
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSEntities dans le schéma.
    /// </summary>
    public partial class FUCHSEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisez un nouvel objet FUCHSEntities.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FUCHSEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "FUCHSModel", "Agenda.FuchsEntities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Agenda.FuchsEntities", global::System.StringComparison.Ordinal))
            {
                return string.Concat("FUCHSModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour COLLABORATEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<COLLABORATEUR> COLLABORATEUR
        {
            get
            {
                if ((this._COLLABORATEUR == null))
                {
                    this._COLLABORATEUR = base.CreateQuery<COLLABORATEUR>("COLLABORATEUR");
                }
                return this._COLLABORATEUR;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<COLLABORATEUR> _COLLABORATEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour Poste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Poste> Poste
        {
            get
            {
                if ((this._Poste == null))
                {
                    this._Poste = base.CreateQuery<Poste>("Poste");
                }
                return this._Poste;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Poste> _Poste;
        /// <summary>
        /// Il n'existe aucun commentaire pour Praticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Praticien> Praticien
        {
            get
            {
                if ((this._Praticien == null))
                {
                    this._Praticien = base.CreateQuery<Praticien>("Praticien");
                }
                return this._Praticien;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Praticien> _Praticien;
        /// <summary>
        /// Il n'existe aucun commentaire pour REGION dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<REGION> REGION
        {
            get
            {
                if ((this._REGION == null))
                {
                    this._REGION = base.CreateQuery<REGION>("REGION");
                }
                return this._REGION;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<REGION> _REGION;
        /// <summary>
        /// Il n'existe aucun commentaire pour RendezVous dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RendezVous> RendezVous
        {
            get
            {
                if ((this._RendezVous == null))
                {
                    this._RendezVous = base.CreateQuery<RendezVous>("RendezVous");
                }
                return this._RendezVous;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RendezVous> _RendezVous;
        /// <summary>
        /// Il n'existe aucun commentaire pour Rôle dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Rôle> Rôle
        {
            get
            {
                if ((this._Rôle == null))
                {
                    this._Rôle = base.CreateQuery<Rôle>("Rôle");
                }
                return this._Rôle;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Rôle> _Rôle;
        /// <summary>
        /// Il n'existe aucun commentaire pour SECTEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SECTEUR> SECTEUR
        {
            get
            {
                if ((this._SECTEUR == null))
                {
                    this._SECTEUR = base.CreateQuery<SECTEUR>("SECTEUR");
                }
                return this._SECTEUR;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SECTEUR> _SECTEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour sysdiagrams dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("sysdiagrams");
                }
                return this._sysdiagrams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// Il n'existe aucun commentaire pour VueRDV dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<VueRDV> VueRDV
        {
            get
            {
                if ((this._VueRDV == null))
                {
                    this._VueRDV = base.CreateQuery<VueRDV>("VueRDV");
                }
                return this._VueRDV;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<VueRDV> _VueRDV;
        /// <summary>
        /// Il n'existe aucun commentaire pour COLLABORATEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCOLLABORATEUR(COLLABORATEUR cOLLABORATEUR)
        {
            base.AddObject("COLLABORATEUR", cOLLABORATEUR);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Poste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPoste(Poste poste)
        {
            base.AddObject("Poste", poste);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Praticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPraticien(Praticien praticien)
        {
            base.AddObject("Praticien", praticien);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour REGION dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToREGION(REGION rEGION)
        {
            base.AddObject("REGION", rEGION);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour RendezVous dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRendezVous(RendezVous rendezVous)
        {
            base.AddObject("RendezVous", rendezVous);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Rôle dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRôle(Rôle rôle)
        {
            base.AddObject("Rôle", rôle);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour SECTEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSECTEUR(SECTEUR sECTEUR)
        {
            base.AddObject("SECTEUR", sECTEUR);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour sysdiagrams dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour VueRDV dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToVueRDV(VueRDV vueRDV)
        {
            base.AddObject("VueRDV", vueRDV);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"FUCHSModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Ent" +
                "ityType Name=\"COLLABORATEUR\"><Key><PropertyRef Name=\"idCollaborateur\" /></Key><P" +
                "roperty Name=\"idCollaborateur\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"18" +
                "\" Scale=\"0\" /><Property Name=\"nomCollaborateur\" Type=\"Edm.String\" MaxLength=\"50\"" +
                " FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"prenomCollaborateur\" Type=" +
                "\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=" +
                "\"adresseCollaborateur\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"cpCollaborateur\" Type=\"Edm.String\" MaxLength=\"50\" F" +
                "ixedLength=\"false\" Unicode=\"true\" /><Property Name=\"villeCollaborateur\" Type=\"Ed" +
                "m.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"da" +
                "teEmbauche\" Type=\"Edm.DateTime\" Precision=\"0\" /><NavigationProperty Name=\"Poste\"" +
                " Relationship=\"FUCHSModel.FK_Poste_Collaborateur\" ToRole=\"Poste\" FromRole=\"COLLA" +
                "BORATEUR\" /><NavigationProperty Name=\"RendezVous\" Relationship=\"FUCHSModel.FK_Re" +
                "ndezVous_COLLABORATEUR\" ToRole=\"RendezVous\" FromRole=\"COLLABORATEUR\" /></EntityT" +
                "ype><EntityType Name=\"Poste\"><Key><PropertyRef Name=\"codeCollaborateur\" /><Prope" +
                "rtyRef Name=\"dateDebutPoste\" /></Key><Property Name=\"dateDebutPoste\" Type=\"Edm.D" +
                "ateTime\" Nullable=\"false\" Precision=\"0\" /><Property Name=\"datefinPoste\" Type=\"Ed" +
                "m.DateTime\" Nullable=\"false\" Precision=\"0\" /><Property Name=\"codeRegion\" Type=\"E" +
                "dm.Decimal\" Precision=\"18\" Scale=\"0\" /><Property Name=\"codeCollaborateur\" Type=\"" +
                "Edm.Decimal\" Nullable=\"false\" Precision=\"18\" Scale=\"0\" /><Property Name=\"codeRôl" +
                "e\" Type=\"Edm.Decimal\" Precision=\"18\" Scale=\"0\" /><Property Name=\"codeSecteur\" Ty" +
                "pe=\"Edm.Decimal\" Precision=\"18\" Scale=\"0\" /><NavigationProperty Name=\"COLLABORAT" +
                "EUR\" Relationship=\"FUCHSModel.FK_Poste_Collaborateur\" ToRole=\"COLLABORATEUR\" Fro" +
                "mRole=\"Poste\" /><NavigationProperty Name=\"REGION\" Relationship=\"FUCHSModel.FK_Po" +
                "ste_Region\" ToRole=\"REGION\" FromRole=\"Poste\" /><NavigationProperty Name=\"Rôle\" R" +
                "elationship=\"FUCHSModel.FK_Poste_Rôle\" ToRole=\"Rôle\" FromRole=\"Poste\" /><Navigat" +
                "ionProperty Name=\"SECTEUR\" Relationship=\"FUCHSModel.FK_Poste_Secteur\" ToRole=\"SE" +
                "CTEUR\" FromRole=\"Poste\" /></EntityType><EntityType Name=\"Praticien\"><Key><Proper" +
                "tyRef Name=\"idPraticien\" /></Key><Property Name=\"idPraticien\" Type=\"Edm.Int32\" N" +
                "ullable=\"false\" /><Property Name=\"nomPraticien\" Type=\"Edm.String\" MaxLength=\"Max" +
                "\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"prenomPraticien\" Type=\"Ed" +
                "m.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><NavigationPropert" +
                "y Name=\"RendezVous\" Relationship=\"FUCHSModel.FK_RendezVous_Praticien\" ToRole=\"Re" +
                "ndezVous\" FromRole=\"Praticien\" /></EntityType><EntityType Name=\"REGION\"><Key><Pr" +
                "opertyRef Name=\"CodeRegion\" /></Key><Property Name=\"CodeRegion\" Type=\"Edm.Decima" +
                "l\" Nullable=\"false\" Precision=\"18\" Scale=\"0\" /><Property Name=\"libelleRegion\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Na" +
                "me=\"SecteurRegion\" Type=\"Edm.Decimal\" Precision=\"18\" Scale=\"0\" /><NavigationProp" +
                "erty Name=\"Poste\" Relationship=\"FUCHSModel.FK_Poste_Region\" ToRole=\"Poste\" FromR" +
                "ole=\"REGION\" /><NavigationProperty Name=\"SECTEUR\" Relationship=\"FUCHSModel.FK_Re" +
                "gion_Secteur\" ToRole=\"SECTEUR\" FromRole=\"REGION\" /></EntityType><EntityType Name" +
                "=\"RendezVous\"><Key><PropertyRef Name=\"dateRdv\" /><PropertyRef Name=\"idCollaborat" +
                "eur\" /></Key><Property Name=\"idPraticien\" Type=\"Edm.Int32\" Nullable=\"false\" /><P" +
                "roperty Name=\"dateRdv\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /><Pro" +
                "perty Name=\"idCollaborateur\" Type=\"Edm.Decimal\" Nullable=\"false\" Precision=\"18\" " +
                "Scale=\"0\" /><NavigationProperty Name=\"COLLABORATEUR\" Relationship=\"FUCHSModel.FK" +
                "_RendezVous_COLLABORATEUR\" ToRole=\"COLLABORATEUR\" FromRole=\"RendezVous\" /><Navig" +
                "ationProperty Name=\"Praticien\" Relationship=\"FUCHSModel.FK_RendezVous_Praticien\"" +
                " ToRole=\"Praticien\" FromRole=\"RendezVous\" /></EntityType><EntityType Name=\"Rôle\"" +
                "><Key><PropertyRef Name=\"codeRôle\" /></Key><Property Name=\"codeRôle\" Type=\"Edm.D" +
                "ecimal\" Nullable=\"false\" Precision=\"18\" Scale=\"0\" /><Property Name=\"libelleRôle\"" +
                " Type=\"Edm.String\" MaxLength=\"25\" FixedLength=\"true\" Unicode=\"true\" /><Navigatio" +
                "nProperty Name=\"Poste\" Relationship=\"FUCHSModel.FK_Poste_Rôle\" ToRole=\"Poste\" Fr" +
                "omRole=\"Rôle\" /></EntityType><EntityType Name=\"SECTEUR\"><Key><PropertyRef Name=\"" +
                "codeSecteur\" /></Key><Property Name=\"codeSecteur\" Type=\"Edm.Decimal\" Nullable=\"f" +
                "alse\" Precision=\"18\" Scale=\"0\" /><Property Name=\"libelleSecteur\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=" +
                "\"Poste\" Relationship=\"FUCHSModel.FK_Poste_Secteur\" ToRole=\"Poste\" FromRole=\"SECT" +
                "EUR\" /><NavigationProperty Name=\"REGION\" Relationship=\"FUCHSModel.FK_Region_Sect" +
                "eur\" ToRole=\"REGION\" FromRole=\"SECTEUR\" /></EntityType><EntityType Name=\"sysdiag" +
                "rams\"><Key><PropertyRef Name=\"diagram_id\" /></Key><Property Name=\"name\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" MaxLength=\"128\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"principal_id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"diagram_id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identi" +
                "ty\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Proper" +
                "ty Name=\"version\" Type=\"Edm.Int32\" /><Property Name=\"definition\" Type=\"Edm.Binar" +
                "y\" MaxLength=\"Max\" FixedLength=\"false\" /></EntityType><EntityType Name=\"VueRDV\">" +
                "<Key><PropertyRef Name=\"dateRdv\" /></Key><Property Name=\"nomCollaborateur\" Type=" +
                "\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=" +
                "\"prenomCollaborateur\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unico" +
                "de=\"true\" /><Property Name=\"nomPraticien\" Type=\"Edm.String\" MaxLength=\"Max\" Fixe" +
                "dLength=\"false\" Unicode=\"true\" /><Property Name=\"prenomPraticien\" Type=\"Edm.Stri" +
                "ng\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"dateRdv\"" +
                " Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /></EntityType><Association " +
                "Name=\"FK_Poste_Collaborateur\"><End Type=\"FUCHSModel.COLLABORATEUR\" Role=\"COLLABO" +
                "RATEUR\" Multiplicity=\"1\" /><End Type=\"FUCHSModel.Poste\" Role=\"Poste\" Multiplicit" +
                "y=\"*\" /><ReferentialConstraint><Principal Role=\"COLLABORATEUR\"><PropertyRef Name" +
                "=\"idCollaborateur\" /></Principal><Dependent Role=\"Poste\"><PropertyRef Name=\"code" +
                "Collaborateur\" /></Dependent></ReferentialConstraint></Association><Association " +
                "Name=\"FK_RendezVous_COLLABORATEUR\"><End Type=\"FUCHSModel.COLLABORATEUR\" Role=\"CO" +
                "LLABORATEUR\" Multiplicity=\"1\" /><End Type=\"FUCHSModel.RendezVous\" Role=\"RendezVo" +
                "us\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"COLLABORATEUR\"><P" +
                "ropertyRef Name=\"idCollaborateur\" /></Principal><Dependent Role=\"RendezVous\"><Pr" +
                "opertyRef Name=\"idCollaborateur\" /></Dependent></ReferentialConstraint></Associa" +
                "tion><Association Name=\"FK_Poste_Region\"><End Type=\"FUCHSModel.REGION\" Role=\"REG" +
                "ION\" Multiplicity=\"0..1\" /><End Type=\"FUCHSModel.Poste\" Role=\"Poste\" Multiplicit" +
                "y=\"*\" /><ReferentialConstraint><Principal Role=\"REGION\"><PropertyRef Name=\"CodeR" +
                "egion\" /></Principal><Dependent Role=\"Poste\"><PropertyRef Name=\"codeRegion\" /></" +
                "Dependent></ReferentialConstraint></Association><Association Name=\"FK_Poste_Rôle" +
                "\"><End Type=\"FUCHSModel.Rôle\" Role=\"Rôle\" Multiplicity=\"0..1\" /><End Type=\"FUCHS" +
                "Model.Poste\" Role=\"Poste\" Multiplicity=\"*\" /><ReferentialCo";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "nstraint><Principal Role=\"Rôle\"><PropertyRef Name=\"codeRôle\" /></Principal><Depen" +
                "dent Role=\"Poste\"><PropertyRef Name=\"codeRôle\" /></Dependent></ReferentialConstr" +
                "aint></Association><Association Name=\"FK_Poste_Secteur\"><End Type=\"FUCHSModel.SE" +
                "CTEUR\" Role=\"SECTEUR\" Multiplicity=\"0..1\" /><End Type=\"FUCHSModel.Poste\" Role=\"P" +
                "oste\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"SECTEUR\"><Prope" +
                "rtyRef Name=\"codeSecteur\" /></Principal><Dependent Role=\"Poste\"><PropertyRef Nam" +
                "e=\"codeSecteur\" /></Dependent></ReferentialConstraint></Association><Association" +
                " Name=\"FK_RendezVous_Praticien\"><End Type=\"FUCHSModel.Praticien\" Role=\"Praticien" +
                "\" Multiplicity=\"1\" /><End Type=\"FUCHSModel.RendezVous\" Role=\"RendezVous\" Multipl" +
                "icity=\"*\" /><ReferentialConstraint><Principal Role=\"Praticien\"><PropertyRef Name" +
                "=\"idPraticien\" /></Principal><Dependent Role=\"RendezVous\"><PropertyRef Name=\"idP" +
                "raticien\" /></Dependent></ReferentialConstraint></Association><Association Name=" +
                "\"FK_Region_Secteur\"><End Type=\"FUCHSModel.SECTEUR\" Role=\"SECTEUR\" Multiplicity=\"" +
                "0..1\" /><End Type=\"FUCHSModel.REGION\" Role=\"REGION\" Multiplicity=\"*\" /><Referent" +
                "ialConstraint><Principal Role=\"SECTEUR\"><PropertyRef Name=\"codeSecteur\" /></Prin" +
                "cipal><Dependent Role=\"REGION\"><PropertyRef Name=\"SecteurRegion\" /></Dependent><" +
                "/ReferentialConstraint></Association></Schema><Schema Namespace=\"KELLER_DAO\" xml" +
                "ns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"FUCHSEn" +
                "tities\" m:IsDefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=" +
                "\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"COLLA" +
                "BORATEUR\" EntityType=\"FUCHSModel.COLLABORATEUR\" /><EntitySet Name=\"Poste\" Entity" +
                "Type=\"FUCHSModel.Poste\" /><EntitySet Name=\"Praticien\" EntityType=\"FUCHSModel.Pra" +
                "ticien\" /><EntitySet Name=\"REGION\" EntityType=\"FUCHSModel.REGION\" /><EntitySet N" +
                "ame=\"RendezVous\" EntityType=\"FUCHSModel.RendezVous\" /><EntitySet Name=\"Rôle\" Ent" +
                "ityType=\"FUCHSModel.Rôle\" /><EntitySet Name=\"SECTEUR\" EntityType=\"FUCHSModel.SEC" +
                "TEUR\" /><EntitySet Name=\"sysdiagrams\" EntityType=\"FUCHSModel.sysdiagrams\" /><Ent" +
                "itySet Name=\"VueRDV\" EntityType=\"FUCHSModel.VueRDV\" /><AssociationSet Name=\"FK_P" +
                "oste_Collaborateur\" Association=\"FUCHSModel.FK_Poste_Collaborateur\"><End Role=\"C" +
                "OLLABORATEUR\" EntitySet=\"COLLABORATEUR\" /><End Role=\"Poste\" EntitySet=\"Poste\" />" +
                "</AssociationSet><AssociationSet Name=\"FK_RendezVous_COLLABORATEUR\" Association=" +
                "\"FUCHSModel.FK_RendezVous_COLLABORATEUR\"><End Role=\"COLLABORATEUR\" EntitySet=\"CO" +
                "LLABORATEUR\" /><End Role=\"RendezVous\" EntitySet=\"RendezVous\" /></AssociationSet>" +
                "<AssociationSet Name=\"FK_Poste_Region\" Association=\"FUCHSModel.FK_Poste_Region\">" +
                "<End Role=\"Poste\" EntitySet=\"Poste\" /><End Role=\"REGION\" EntitySet=\"REGION\" /></" +
                "AssociationSet><AssociationSet Name=\"FK_Poste_Rôle\" Association=\"FUCHSModel.FK_P" +
                "oste_Rôle\"><End Role=\"Poste\" EntitySet=\"Poste\" /><End Role=\"Rôle\" EntitySet=\"Rôl" +
                "e\" /></AssociationSet><AssociationSet Name=\"FK_Poste_Secteur\" Association=\"FUCHS" +
                "Model.FK_Poste_Secteur\"><End Role=\"Poste\" EntitySet=\"Poste\" /><End Role=\"SECTEUR" +
                "\" EntitySet=\"SECTEUR\" /></AssociationSet><AssociationSet Name=\"FK_RendezVous_Pra" +
                "ticien\" Association=\"FUCHSModel.FK_RendezVous_Praticien\"><End Role=\"Praticien\" E" +
                "ntitySet=\"Praticien\" /><End Role=\"RendezVous\" EntitySet=\"RendezVous\" /></Associa" +
                "tionSet><AssociationSet Name=\"FK_Region_Secteur\" Association=\"FUCHSModel.FK_Regi" +
                "on_Secteur\"><End Role=\"REGION\" EntitySet=\"REGION\" /><End Role=\"SECTEUR\" EntitySe" +
                "t=\"SECTEUR\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></" +
                "edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.COLLABORATEUR dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// idCollaborateur
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("COLLABORATEUR")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("idCollaborateur")]
    public partial class COLLABORATEUR : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet COLLABORATEUR.
        /// </summary>
        /// <param name="idCollaborateur">Valeur initiale de idCollaborateur.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static COLLABORATEUR CreateCOLLABORATEUR(decimal idCollaborateur)
        {
            COLLABORATEUR cOLLABORATEUR = new COLLABORATEUR();
            cOLLABORATEUR.idCollaborateur = idCollaborateur;
            return cOLLABORATEUR;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal idCollaborateur
        {
            get
            {
                return this._idCollaborateur;
            }
            set
            {
                this.OnidCollaborateurChanging(value);
                this._idCollaborateur = value;
                this.OnidCollaborateurChanged();
                this.OnPropertyChanged("idCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _idCollaborateur;
        partial void OnidCollaborateurChanging(decimal value);
        partial void OnidCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nomCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nomCollaborateur
        {
            get
            {
                return this._nomCollaborateur;
            }
            set
            {
                this.OnnomCollaborateurChanging(value);
                this._nomCollaborateur = value;
                this.OnnomCollaborateurChanged();
                this.OnPropertyChanged("nomCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nomCollaborateur;
        partial void OnnomCollaborateurChanging(string value);
        partial void OnnomCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prenomCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prenomCollaborateur
        {
            get
            {
                return this._prenomCollaborateur;
            }
            set
            {
                this.OnprenomCollaborateurChanging(value);
                this._prenomCollaborateur = value;
                this.OnprenomCollaborateurChanged();
                this.OnPropertyChanged("prenomCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prenomCollaborateur;
        partial void OnprenomCollaborateurChanging(string value);
        partial void OnprenomCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété adresseCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string adresseCollaborateur
        {
            get
            {
                return this._adresseCollaborateur;
            }
            set
            {
                this.OnadresseCollaborateurChanging(value);
                this._adresseCollaborateur = value;
                this.OnadresseCollaborateurChanged();
                this.OnPropertyChanged("adresseCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _adresseCollaborateur;
        partial void OnadresseCollaborateurChanging(string value);
        partial void OnadresseCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété cpCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string cpCollaborateur
        {
            get
            {
                return this._cpCollaborateur;
            }
            set
            {
                this.OncpCollaborateurChanging(value);
                this._cpCollaborateur = value;
                this.OncpCollaborateurChanged();
                this.OnPropertyChanged("cpCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _cpCollaborateur;
        partial void OncpCollaborateurChanging(string value);
        partial void OncpCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété villeCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string villeCollaborateur
        {
            get
            {
                return this._villeCollaborateur;
            }
            set
            {
                this.OnvilleCollaborateurChanging(value);
                this._villeCollaborateur = value;
                this.OnvilleCollaborateurChanged();
                this.OnPropertyChanged("villeCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _villeCollaborateur;
        partial void OnvilleCollaborateurChanging(string value);
        partial void OnvilleCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateEmbauche dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dateEmbauche
        {
            get
            {
                return this._dateEmbauche;
            }
            set
            {
                this.OndateEmbaucheChanging(value);
                this._dateEmbauche = value;
                this.OndateEmbaucheChanged();
                this.OnPropertyChanged("dateEmbauche");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateEmbauche;
        partial void OndateEmbaucheChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateEmbaucheChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Poste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Poste> Poste
        {
            get
            {
                return this._Poste;
            }
            set
            {
                this._Poste = value;
                this.OnPropertyChanged("Poste");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Poste> _Poste = new global::System.Data.Services.Client.DataServiceCollection<Poste>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour RendezVous dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RendezVous> RendezVous
        {
            get
            {
                return this._RendezVous;
            }
            set
            {
                this._RendezVous = value;
                this.OnPropertyChanged("RendezVous");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RendezVous> _RendezVous = new global::System.Data.Services.Client.DataServiceCollection<RendezVous>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.Poste dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// codeCollaborateur
    /// dateDebutPoste
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Poste")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("codeCollaborateur", "dateDebutPoste")]
    public partial class Poste : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Poste.
        /// </summary>
        /// <param name="dateDebutPoste">Valeur initiale de dateDebutPoste.</param>
        /// <param name="datefinPoste">Valeur initiale de datefinPoste.</param>
        /// <param name="codeCollaborateur">Valeur initiale de codeCollaborateur.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Poste CreatePoste(global::System.DateTime dateDebutPoste, global::System.DateTime datefinPoste, decimal codeCollaborateur)
        {
            Poste poste = new Poste();
            poste.dateDebutPoste = dateDebutPoste;
            poste.datefinPoste = datefinPoste;
            poste.codeCollaborateur = codeCollaborateur;
            return poste;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateDebutPoste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime dateDebutPoste
        {
            get
            {
                return this._dateDebutPoste;
            }
            set
            {
                this.OndateDebutPosteChanging(value);
                this._dateDebutPoste = value;
                this.OndateDebutPosteChanged();
                this.OnPropertyChanged("dateDebutPoste");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _dateDebutPoste;
        partial void OndateDebutPosteChanging(global::System.DateTime value);
        partial void OndateDebutPosteChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété datefinPoste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime datefinPoste
        {
            get
            {
                return this._datefinPoste;
            }
            set
            {
                this.OndatefinPosteChanging(value);
                this._datefinPoste = value;
                this.OndatefinPosteChanged();
                this.OnPropertyChanged("datefinPoste");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _datefinPoste;
        partial void OndatefinPosteChanging(global::System.DateTime value);
        partial void OndatefinPosteChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codeRegion dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> codeRegion
        {
            get
            {
                return this._codeRegion;
            }
            set
            {
                this.OncodeRegionChanging(value);
                this._codeRegion = value;
                this.OncodeRegionChanged();
                this.OnPropertyChanged("codeRegion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _codeRegion;
        partial void OncodeRegionChanging(global::System.Nullable<decimal> value);
        partial void OncodeRegionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codeCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal codeCollaborateur
        {
            get
            {
                return this._codeCollaborateur;
            }
            set
            {
                this.OncodeCollaborateurChanging(value);
                this._codeCollaborateur = value;
                this.OncodeCollaborateurChanged();
                this.OnPropertyChanged("codeCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _codeCollaborateur;
        partial void OncodeCollaborateurChanging(decimal value);
        partial void OncodeCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codeRôle dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> codeRôle
        {
            get
            {
                return this._codeRôle;
            }
            set
            {
                this.OncodeRôleChanging(value);
                this._codeRôle = value;
                this.OncodeRôleChanged();
                this.OnPropertyChanged("codeRôle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _codeRôle;
        partial void OncodeRôleChanging(global::System.Nullable<decimal> value);
        partial void OncodeRôleChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codeSecteur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> codeSecteur
        {
            get
            {
                return this._codeSecteur;
            }
            set
            {
                this.OncodeSecteurChanging(value);
                this._codeSecteur = value;
                this.OncodeSecteurChanged();
                this.OnPropertyChanged("codeSecteur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _codeSecteur;
        partial void OncodeSecteurChanging(global::System.Nullable<decimal> value);
        partial void OncodeSecteurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour COLLABORATEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public COLLABORATEUR COLLABORATEUR
        {
            get
            {
                return this._COLLABORATEUR;
            }
            set
            {
                this._COLLABORATEUR = value;
                this.OnPropertyChanged("COLLABORATEUR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private COLLABORATEUR _COLLABORATEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour REGION dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public REGION REGION
        {
            get
            {
                return this._REGION;
            }
            set
            {
                this._REGION = value;
                this.OnPropertyChanged("REGION");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private REGION _REGION;
        /// <summary>
        /// Il n'existe aucun commentaire pour Rôle dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Rôle Rôle
        {
            get
            {
                return this._Rôle;
            }
            set
            {
                this._Rôle = value;
                this.OnPropertyChanged("Rôle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Rôle _Rôle;
        /// <summary>
        /// Il n'existe aucun commentaire pour SECTEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SECTEUR SECTEUR
        {
            get
            {
                return this._SECTEUR;
            }
            set
            {
                this._SECTEUR = value;
                this.OnPropertyChanged("SECTEUR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SECTEUR _SECTEUR;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.Praticien dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// idPraticien
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Praticien")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("idPraticien")]
    public partial class Praticien : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Praticien.
        /// </summary>
        /// <param name="idPraticien">Valeur initiale de idPraticien.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Praticien CreatePraticien(int idPraticien)
        {
            Praticien praticien = new Praticien();
            praticien.idPraticien = idPraticien;
            return praticien;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idPraticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int idPraticien
        {
            get
            {
                return this._idPraticien;
            }
            set
            {
                this.OnidPraticienChanging(value);
                this._idPraticien = value;
                this.OnidPraticienChanged();
                this.OnPropertyChanged("idPraticien");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _idPraticien;
        partial void OnidPraticienChanging(int value);
        partial void OnidPraticienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nomPraticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nomPraticien
        {
            get
            {
                return this._nomPraticien;
            }
            set
            {
                this.OnnomPraticienChanging(value);
                this._nomPraticien = value;
                this.OnnomPraticienChanged();
                this.OnPropertyChanged("nomPraticien");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nomPraticien;
        partial void OnnomPraticienChanging(string value);
        partial void OnnomPraticienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prenomPraticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prenomPraticien
        {
            get
            {
                return this._prenomPraticien;
            }
            set
            {
                this.OnprenomPraticienChanging(value);
                this._prenomPraticien = value;
                this.OnprenomPraticienChanged();
                this.OnPropertyChanged("prenomPraticien");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prenomPraticien;
        partial void OnprenomPraticienChanging(string value);
        partial void OnprenomPraticienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour RendezVous dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RendezVous> RendezVous
        {
            get
            {
                return this._RendezVous;
            }
            set
            {
                this._RendezVous = value;
                this.OnPropertyChanged("RendezVous");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RendezVous> _RendezVous = new global::System.Data.Services.Client.DataServiceCollection<RendezVous>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.REGION dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// CodeRegion
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("REGION")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CodeRegion")]
    public partial class REGION : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet REGION.
        /// </summary>
        /// <param name="codeRegion">Valeur initiale de CodeRegion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static REGION CreateREGION(decimal codeRegion)
        {
            REGION rEGION = new REGION();
            rEGION.CodeRegion = codeRegion;
            return rEGION;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété CodeRegion dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal CodeRegion
        {
            get
            {
                return this._CodeRegion;
            }
            set
            {
                this.OnCodeRegionChanging(value);
                this._CodeRegion = value;
                this.OnCodeRegionChanged();
                this.OnPropertyChanged("CodeRegion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _CodeRegion;
        partial void OnCodeRegionChanging(decimal value);
        partial void OnCodeRegionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété libelleRegion dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string libelleRegion
        {
            get
            {
                return this._libelleRegion;
            }
            set
            {
                this.OnlibelleRegionChanging(value);
                this._libelleRegion = value;
                this.OnlibelleRegionChanged();
                this.OnPropertyChanged("libelleRegion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _libelleRegion;
        partial void OnlibelleRegionChanging(string value);
        partial void OnlibelleRegionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété SecteurRegion dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> SecteurRegion
        {
            get
            {
                return this._SecteurRegion;
            }
            set
            {
                this.OnSecteurRegionChanging(value);
                this._SecteurRegion = value;
                this.OnSecteurRegionChanged();
                this.OnPropertyChanged("SecteurRegion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _SecteurRegion;
        partial void OnSecteurRegionChanging(global::System.Nullable<decimal> value);
        partial void OnSecteurRegionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Poste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Poste> Poste
        {
            get
            {
                return this._Poste;
            }
            set
            {
                this._Poste = value;
                this.OnPropertyChanged("Poste");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Poste> _Poste = new global::System.Data.Services.Client.DataServiceCollection<Poste>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour SECTEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SECTEUR SECTEUR
        {
            get
            {
                return this._SECTEUR;
            }
            set
            {
                this._SECTEUR = value;
                this.OnPropertyChanged("SECTEUR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SECTEUR _SECTEUR;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.RendezVous dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// dateRdv
    /// idCollaborateur
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RendezVous")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("dateRdv", "idCollaborateur")]
    public partial class RendezVous : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet RendezVous.
        /// </summary>
        /// <param name="idPraticien">Valeur initiale de idPraticien.</param>
        /// <param name="dateRdv">Valeur initiale de dateRdv.</param>
        /// <param name="idCollaborateur">Valeur initiale de idCollaborateur.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RendezVous CreateRendezVous(int idPraticien, global::System.DateTime dateRdv, decimal idCollaborateur)
        {
            RendezVous rendezVous = new RendezVous();
            rendezVous.idPraticien = idPraticien;
            rendezVous.dateRdv = dateRdv;
            rendezVous.idCollaborateur = idCollaborateur;
            return rendezVous;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idPraticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int idPraticien
        {
            get
            {
                return this._idPraticien;
            }
            set
            {
                this.OnidPraticienChanging(value);
                this._idPraticien = value;
                this.OnidPraticienChanged();
                this.OnPropertyChanged("idPraticien");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _idPraticien;
        partial void OnidPraticienChanging(int value);
        partial void OnidPraticienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateRdv dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime dateRdv
        {
            get
            {
                return this._dateRdv;
            }
            set
            {
                this.OndateRdvChanging(value);
                this._dateRdv = value;
                this.OndateRdvChanged();
                this.OnPropertyChanged("dateRdv");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _dateRdv;
        partial void OndateRdvChanging(global::System.DateTime value);
        partial void OndateRdvChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété idCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal idCollaborateur
        {
            get
            {
                return this._idCollaborateur;
            }
            set
            {
                this.OnidCollaborateurChanging(value);
                this._idCollaborateur = value;
                this.OnidCollaborateurChanged();
                this.OnPropertyChanged("idCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _idCollaborateur;
        partial void OnidCollaborateurChanging(decimal value);
        partial void OnidCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour COLLABORATEUR dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public COLLABORATEUR COLLABORATEUR
        {
            get
            {
                return this._COLLABORATEUR;
            }
            set
            {
                this._COLLABORATEUR = value;
                this.OnPropertyChanged("COLLABORATEUR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private COLLABORATEUR _COLLABORATEUR;
        /// <summary>
        /// Il n'existe aucun commentaire pour Praticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Praticien Praticien
        {
            get
            {
                return this._Praticien;
            }
            set
            {
                this._Praticien = value;
                this.OnPropertyChanged("Praticien");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Praticien _Praticien;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.Rôle dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// codeRôle
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Rôle")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("codeRôle")]
    public partial class Rôle : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Rôle.
        /// </summary>
        /// <param name="codeRôle">Valeur initiale de codeRôle.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Rôle CreateRôle(decimal codeRôle)
        {
            Rôle rôle = new Rôle();
            rôle.codeRôle = codeRôle;
            return rôle;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codeRôle dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal codeRôle
        {
            get
            {
                return this._codeRôle;
            }
            set
            {
                this.OncodeRôleChanging(value);
                this._codeRôle = value;
                this.OncodeRôleChanged();
                this.OnPropertyChanged("codeRôle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _codeRôle;
        partial void OncodeRôleChanging(decimal value);
        partial void OncodeRôleChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété libelleRôle dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string libelleRôle
        {
            get
            {
                return this._libelleRôle;
            }
            set
            {
                this.OnlibelleRôleChanging(value);
                this._libelleRôle = value;
                this.OnlibelleRôleChanged();
                this.OnPropertyChanged("libelleRôle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _libelleRôle;
        partial void OnlibelleRôleChanging(string value);
        partial void OnlibelleRôleChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Poste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Poste> Poste
        {
            get
            {
                return this._Poste;
            }
            set
            {
                this._Poste = value;
                this.OnPropertyChanged("Poste");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Poste> _Poste = new global::System.Data.Services.Client.DataServiceCollection<Poste>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.SECTEUR dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// codeSecteur
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SECTEUR")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("codeSecteur")]
    public partial class SECTEUR : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet SECTEUR.
        /// </summary>
        /// <param name="codeSecteur">Valeur initiale de codeSecteur.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SECTEUR CreateSECTEUR(decimal codeSecteur)
        {
            SECTEUR sECTEUR = new SECTEUR();
            sECTEUR.codeSecteur = codeSecteur;
            return sECTEUR;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codeSecteur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal codeSecteur
        {
            get
            {
                return this._codeSecteur;
            }
            set
            {
                this.OncodeSecteurChanging(value);
                this._codeSecteur = value;
                this.OncodeSecteurChanged();
                this.OnPropertyChanged("codeSecteur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _codeSecteur;
        partial void OncodeSecteurChanging(decimal value);
        partial void OncodeSecteurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété libelleSecteur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string libelleSecteur
        {
            get
            {
                return this._libelleSecteur;
            }
            set
            {
                this.OnlibelleSecteurChanging(value);
                this._libelleSecteur = value;
                this.OnlibelleSecteurChanged();
                this.OnPropertyChanged("libelleSecteur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _libelleSecteur;
        partial void OnlibelleSecteurChanging(string value);
        partial void OnlibelleSecteurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Poste dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Poste> Poste
        {
            get
            {
                return this._Poste;
            }
            set
            {
                this._Poste = value;
                this.OnPropertyChanged("Poste");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Poste> _Poste = new global::System.Data.Services.Client.DataServiceCollection<Poste>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour REGION dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<REGION> REGION
        {
            get
            {
                return this._REGION;
            }
            set
            {
                this._REGION = value;
                this.OnPropertyChanged("REGION");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<REGION> _REGION = new global::System.Data.Services.Client.DataServiceCollection<REGION>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.sysdiagrams dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("sysdiagrams")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("diagram_id")]
    public partial class sysdiagrams : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de name.</param>
        /// <param name="principal_id">Valeur initiale de principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de diagram_id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété name dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété principal_id dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this._principal_id = value;
                this.Onprincipal_idChanged();
                this.OnPropertyChanged("principal_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété diagram_id dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this._diagram_id = value;
                this.Ondiagram_idChanged();
                this.OnPropertyChanged("diagram_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété version dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this._version = value;
                this.OnversionChanged();
                this.OnPropertyChanged("version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété definition dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] definition
        {
            get
            {
                if ((this._definition != null))
                {
                    return ((byte[])(this._definition.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OndefinitionChanging(value);
                this._definition = value;
                this.OndefinitionChanged();
                this.OnPropertyChanged("definition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour FUCHSModel.VueRDV dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// dateRdv
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("VueRDV")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("dateRdv")]
    public partial class VueRDV : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet VueRDV.
        /// </summary>
        /// <param name="dateRdv">Valeur initiale de dateRdv.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static VueRDV CreateVueRDV(global::System.DateTime dateRdv)
        {
            VueRDV vueRDV = new VueRDV();
            vueRDV.dateRdv = dateRdv;
            return vueRDV;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nomCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nomCollaborateur
        {
            get
            {
                return this._nomCollaborateur;
            }
            set
            {
                this.OnnomCollaborateurChanging(value);
                this._nomCollaborateur = value;
                this.OnnomCollaborateurChanged();
                this.OnPropertyChanged("nomCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nomCollaborateur;
        partial void OnnomCollaborateurChanging(string value);
        partial void OnnomCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prenomCollaborateur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prenomCollaborateur
        {
            get
            {
                return this._prenomCollaborateur;
            }
            set
            {
                this.OnprenomCollaborateurChanging(value);
                this._prenomCollaborateur = value;
                this.OnprenomCollaborateurChanged();
                this.OnPropertyChanged("prenomCollaborateur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prenomCollaborateur;
        partial void OnprenomCollaborateurChanging(string value);
        partial void OnprenomCollaborateurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété nomPraticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nomPraticien
        {
            get
            {
                return this._nomPraticien;
            }
            set
            {
                this.OnnomPraticienChanging(value);
                this._nomPraticien = value;
                this.OnnomPraticienChanged();
                this.OnPropertyChanged("nomPraticien");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nomPraticien;
        partial void OnnomPraticienChanging(string value);
        partial void OnnomPraticienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété prenomPraticien dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prenomPraticien
        {
            get
            {
                return this._prenomPraticien;
            }
            set
            {
                this.OnprenomPraticienChanging(value);
                this._prenomPraticien = value;
                this.OnprenomPraticienChanged();
                this.OnPropertyChanged("prenomPraticien");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prenomPraticien;
        partial void OnprenomPraticienChanging(string value);
        partial void OnprenomPraticienChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété dateRdv dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime dateRdv
        {
            get
            {
                return this._dateRdv;
            }
            set
            {
                this.OndateRdvChanging(value);
                this._dateRdv = value;
                this.OndateRdvChanged();
                this.OnPropertyChanged("dateRdv");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _dateRdv;
        partial void OndateRdvChanging(global::System.DateTime value);
        partial void OndateRdvChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
